# Generated by Django 3.1.3 on 2020-11-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, null=True, verbose_name='Título')),
                ('description', models.TextField(max_length=700, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='nosotros/', verbose_name='Imagen')),
                ('videofile', models.FileField(null=True, upload_to='nosotros/', verbose_name='Video')),
                ('direccion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('skype', models.URLField(blank=True, null=True, verbose_name='Skype')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
            ],
            options={
                'verbose_name': 'Nos',
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=40, null=True, verbose_name='Nombre del Proyecto')),
                ('año', models.DateTimeField(auto_now_add=True, verbose_name='Año del Proyecto')),
                ('descripcion', models.CharField(max_length=300, null=True, verbose_name='Descripción')),
                ('logros', models.CharField(max_length=300, null=True, verbose_name='Logros')),
                ('imagen', models.ImageField(upload_to='imagesProyecto/', verbose_name='Imagen General')),
                ('link', models.URLField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['año'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('texto', models.CharField(max_length=300, verbose_name='Testimonio')),
                ('foto', models.ImageField(upload_to='fotoTestimonio/', verbose_name='Foto')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.proyecto', verbose_name='Proyecto Vinculado')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha')),
                ('link', models.URLField(blank=True, max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='TÍtulo de la Noticia')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción de la Noticia')),
                ('imagen', models.ImageField(default='noticia.jpg', upload_to='noticia/', verbose_name='Imagen')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Contenido de la Noticia')),
                ('destacados', models.BooleanField(default=False, editable=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-created', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Imagen_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloProyecto', models.CharField(blank=True, max_length=400, null=True)),
                ('images', models.FileField(upload_to='imagesProyecto/')),
                ('imagenes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.proyecto', verbose_name='Imagenes Extras')),
            ],
            options={
                'verbose_name': 'Imagen_Proyecto',
                'verbose_name_plural': 'Imagenes_Proyectos',
            },
        ),
    ]
